### ISSUE TITLE
Direct Media freezes BetterDiscord

### ISSUE THREAD

**Issue by Spartan322** [samfun123/script-storage#1]
The program will become unresponsive and will no longer function, the only way to fix it is to end all Discord processes in the task manager, start Discord back up, and disable Direct Media before opening a server

**Comment by samfundev** [comment]
I've tried to replicate this issue but I can't get discord to become unresponsive. Please make sure that you're using the latest version of Direct Media.

**Comment by Spartan322** [comment]
Using the version seen on this repo, I have been able to replicate the issue by simply switching channels, it does not appear to react when being enabled, but does react upon a channel change (possibly cause the original channel had no media on it, not sure), and freezes the entire application.

Edit: It seems something is performing an infinite loop, making a long period of unresponsiveness followed by an unfathomably long chain of repeating data, most notably images. After this happens, BD becomes unresponsive again.

**Comment by samfundev** [comment]
Could you try to disable all other plugins and see if the problem still persists. If it doesn't re enable each plugin one at a time and see if another plugin is conflicting with my plugin.

**Comment by Spartan322** [comment]
I see about it within two days and edit this response on my findings.
