### ISSUE TITLE
IP logging issue.

### ISSUE THREAD

**Issue by CoolCorrect** [samfun123/script-storage#2]
This automatic link unshortener uses your IP address to resolve the links. That means that if someone wants to IP log you, you don't even have to click the link. They just send you a link, and the auto link unshortener clicks it for you. I got this plugin to prevent from that, but in my tests this seems to do the opposite. It'd be a very nice feature if IP logging didn't exist, or it had some sort of protection against it even. If the creator sees this, I'd like to suggest a fix or some warning that this is an issue.

**Comment by samfundev** [comment]
I've fixed this by allowing users to use an API to unshorten the URL. If you have anymore issues with this feel free to let me know.
